//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKShipmentServices
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://impl.server.order.services.wbs.osms.sf.com/", ConfigurationName="HKShipmentServices.OrderWebService")]
    public interface OrderWebService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<HKShipmentServices.sfexpressServiceResponse> sfexpressServiceAsync(HKShipmentServices.sfexpressService request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<HKShipmentServices.expressServiceResponse> expressServiceAsync(HKShipmentServices.expressService request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sfexpressService
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sfexpressService", Namespace="http://impl.server.order.services.wbs.osms.sf.com/", Order=0)]
        public HKShipmentServices.sfexpressServiceBody Body;
        
        public sfexpressService()
        {
        }
        
        public sfexpressService(HKShipmentServices.sfexpressServiceBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class sfexpressServiceBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string validateStr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string customerCode;
        
        public sfexpressServiceBody()
        {
        }
        
        public sfexpressServiceBody(string data, string validateStr, string customerCode)
        {
            this.data = data;
            this.validateStr = validateStr;
            this.customerCode = customerCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sfexpressServiceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sfexpressServiceResponse", Namespace="http://impl.server.order.services.wbs.osms.sf.com/", Order=0)]
        public HKShipmentServices.sfexpressServiceResponseBody Body;
        
        public sfexpressServiceResponse()
        {
        }
        
        public sfexpressServiceResponse(HKShipmentServices.sfexpressServiceResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class sfexpressServiceResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Return;
        
        public sfexpressServiceResponseBody()
        {
        }
        
        public sfexpressServiceResponseBody(string Return)
        {
            this.Return = Return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class expressService
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="expressService", Namespace="http://impl.server.order.services.wbs.osms.sf.com/", Order=0)]
        public HKShipmentServices.expressServiceBody Body;
        
        public expressService()
        {
        }
        
        public expressService(HKShipmentServices.expressServiceBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class expressServiceBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] byteData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string verifyCode;
        
        public expressServiceBody()
        {
        }
        
        public expressServiceBody(byte[] byteData, string verifyCode)
        {
            this.byteData = byteData;
            this.verifyCode = verifyCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class expressServiceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="expressServiceResponse", Namespace="http://impl.server.order.services.wbs.osms.sf.com/", Order=0)]
        public HKShipmentServices.expressServiceResponseBody Body;
        
        public expressServiceResponse()
        {
        }
        
        public expressServiceResponse(HKShipmentServices.expressServiceResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class expressServiceResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] Return;
        
        public expressServiceResponseBody()
        {
        }
        
        public expressServiceResponseBody(byte[] Return)
        {
            this.Return = Return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface OrderWebServiceChannel : HKShipmentServices.OrderWebService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class OrderWebServiceClient : System.ServiceModel.ClientBase<HKShipmentServices.OrderWebService>, HKShipmentServices.OrderWebService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OrderWebServiceClient() : 
                base(OrderWebServiceClient.GetDefaultBinding(), OrderWebServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.OrderWebServiceImplPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrderWebServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(OrderWebServiceClient.GetBindingForEndpoint(endpointConfiguration), OrderWebServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrderWebServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OrderWebServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrderWebServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OrderWebServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrderWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HKShipmentServices.sfexpressServiceResponse> HKShipmentServices.OrderWebService.sfexpressServiceAsync(HKShipmentServices.sfexpressService request)
        {
            return base.Channel.sfexpressServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<HKShipmentServices.sfexpressServiceResponse> sfexpressServiceAsync(string data, string validateStr, string customerCode)
        {
            HKShipmentServices.sfexpressService inValue = new HKShipmentServices.sfexpressService();
            inValue.Body = new HKShipmentServices.sfexpressServiceBody();
            inValue.Body.data = data;
            inValue.Body.validateStr = validateStr;
            inValue.Body.customerCode = customerCode;
            return ((HKShipmentServices.OrderWebService)(this)).sfexpressServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HKShipmentServices.expressServiceResponse> HKShipmentServices.OrderWebService.expressServiceAsync(HKShipmentServices.expressService request)
        {
            return base.Channel.expressServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<HKShipmentServices.expressServiceResponse> expressServiceAsync(byte[] byteData, string verifyCode)
        {
            HKShipmentServices.expressService inValue = new HKShipmentServices.expressService();
            inValue.Body = new HKShipmentServices.expressServiceBody();
            inValue.Body.byteData = byteData;
            inValue.Body.verifyCode = verifyCode;
            return ((HKShipmentServices.OrderWebService)(this)).expressServiceAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OrderWebServiceImplPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OrderWebServiceImplPort))
            {
                return new System.ServiceModel.EndpointAddress("http://osms.sit.sf-express.com:2080/osms/services/OrderWebService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return OrderWebServiceClient.GetBindingForEndpoint(EndpointConfiguration.OrderWebServiceImplPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return OrderWebServiceClient.GetEndpointAddress(EndpointConfiguration.OrderWebServiceImplPort);
        }
        
        public enum EndpointConfiguration
        {
            
            OrderWebServiceImplPort,
        }
    }
}
