export const SFErrors = {
  '6119': 'Consignee’s phone number(d_tel) is null', 
  '6120': 'S.F service/product (express_type) is null',
  '6121': 'Shipper’s phone number(j_tel) is null ',
  '6122': 'Invalid filtering type(filter_type) ',
  '6123': 'S.F.waybill number(mailno) is null ',
  '6124': 'Payment method(pay_method) is null ',
  '6125': 'Mandatory field is missing for Element ‘Order/Cargo’ ',
  '6126': 'Invalid S.F.monthly - payment account number(custid) ',
  '6127': 'Name of S.F.VAS(property ‘name’ of element ‘Order / AddedService’) is null ',
  '6128': 'Invalid name of S.F.VAS(property ‘name’ of element ‘Order / AddedService’) ',
  '6129': 'Invalid payment method(pay_method) ',
  '6130': 'Invalid total volume of commodity(s)(volume) ',
  '6131': 'Invalid customer order handling indicator(dealtype) ',
  '6132': 'Invalid type of tracking method(method_type) ',
  '6133': 'Invalid type of tracking number(tracking_type) ',
  '6134': 'Invalid request XML message, order filtering is failed ',
  '6135': 'Invalid request XML message, order placing is failed ',
  '6136': 'Invalid request XML message, order confirming / cancelling is failed ',
  '6137': 'Invalid request XML message, route track and trace is failed ',
  '6138': 'Invalid COD amount(property ‘value’ of element ‘Order / AddedService’) ',
  '6139': 'Invalid COD amount(property ‘value’ of element ‘Order / AddedService’), should not be less than 0 ',
  '6140': 'COD service account number(property ‘value1’ of element ‘Order/ AddedService’) is null',
  '6141': 'Invalid COD service account number(property ‘value1’ of element ‘Order / AddedService’), COD amount limit is not configured',
  '6142': 'Invalid COD amount(property ‘value’ of element ‘Order / AddedService’), COD amount exceeds limit',
  '6150': 'Customer order number(orderid) does not exist',
  '8000': 'Invalid message parameter',
  '8001': 'Unauthorized IP',
  '8002': 'Unauthorized usage of this interface',
  '8003': 'Batch transaction exceeds limit(element ‘OrderFilter’)',
  '8004': 'Batch transaction exceeds limit(tracking number, property ‘tracking_number’)',
  '8005': 'Count of query exceeds limit',
  '8009': 'Customer order is out of S.F.service area coverage, order confirming is failed',
  '8010': 'Customer order is not filtered, order confirming is failed',
  '8011': 'Access number and S.F.waybill number(mailno) do not match ',
  '8012': 'Access number and customer order number(orderid) do not match ',
  '8013': 'Tracking number(tracking_number) is null, route track and trace is failed',
  '8014': 'Verification code error',
  '8015': 'S.F.main - waybill number(main_mailno) is null, sub - waybill applying is failed',
  '8016': 'Duplicate customer order number(orderid)',
  '8017': 'Customer order number(orderid) and S.F.waybill number(mailno) do not match ',
  '8018': 'Customer order information is not received',
  '8019': 'Customer order number(orderid) is already confirmed',
  '8020': 'Customer order number(orderid) and S.F.waybill number(mailno) do not match ',
  '8021': 'Access number is null',
  '8023': 'Service name is null',
  '8024': 'No S.F.waybill number exist for this customer order number, order confirming / cancelling is failed',
  '8025': 'Service name is null / Invalid service name',
  '8026': 'Access number does not exist',
  '8027': 'Business template does not exist',
  '8028': 'Business template configuration / property is not set',
  '8029': 'The default business template is not configured',
  '8030': 'Validate template is not found for this time slot ',
  '8031': 'Data error, business template not found',
  '8032': 'Data error, business template configuration not found',
  '8033': 'Data error, business template property not found',
  '8034': 'Duplicate registration for manual filtering result pushing',
  '8035': 'S.F.waybill number is null, automatic customer order confirming is failed',
  '8036': 'S.F.waybill number is null, Route track and trace pushing registration is failed',
  '8037': 'Customer order number is already cancelled',
  '8039': 'Invalid S.F.service / product(business_type), transit time query is failed',
  '8040': 'Origin area code(code) cannot be retrieved, transit time query is failed',
  '8041': 'Destination area code(code) cannot be retrieved, transit time query is failed',
  '8042': 'Invalid pickup time(consigned_time)',
  '8066': 'Invalid count of parcel(s) new added(parcel_quantity), sub - waybill applying is failed',
  '8067': 'Count of parcel(s) new added(parcel_quantity) exceeds limit, sub - waybill applying is failed',
  '8068': 'Manifest of S.F.waybill number was already generated, sub - waybill applying is failed',
  '8069': 'Customer order is out of S.F.service area coverage, sub - waybill applying is failed ',

};
